Apple Unified Logging System Support (#46)
* Added `UnifiedLoggingWriter` for writing to the Apple Unified Logging System. 
* Remove OS_ACTIVITY_MODE disable from example schemes so os_log output writes to logs.
* Update podspec version and run pod update.
* Change test and example platform for OSX to 10.12.
* Removing performance tests that write to standard out.
* Removing Swiftlint.
* Removing xcpretty to simplify build.
* Remove stdout performance tests on ObjC.
* Remove playground and xctest_tool.rb
* Removing older tests for 9.3.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,21 +9,21 @@ env:
 
 matrix:
   include:
-    - 
+    -
       os: linux
       dist: trusty
       sudo: required
-      env: 
-         - BUILD="swift build"
-    - 
-      os: osx
-      osx_image: xcode9.3
-      env: 
+      env:
          - BUILD="swift build"
     -
       os: osx
       osx_image: xcode9.3
-      env: 
+      env:
+         - BUILD="swift build"
+    -
+      os: osx
+      osx_image: xcode9.3
+      env:
          - BUILD="pod lint"
     -
       os: osx
@@ -33,54 +33,15 @@ matrix:
          - TEST_DEST="platform=iOS Simulator,OS=11.3,name=iPhone 8"
          - TEST_SDK=iphonesimulator
          - SCHEME=TraceLog-iOS-Example
-    - 
+
+    -
       os: osx
       osx_image: xcode9.3
-      env: 
+      env:
          - BUILD="xcodebuild"
-         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6s"
-         - TEST_SDK=iphonesimulator
-         - SCHEME=TraceLog-iOS-Example 
-    - 
-      os: osx
-      osx_image: xcode9.3
-      env: 
-         - BUILD="xcodebuild"
-         - TEST_DEST="platform=iOS Simulator,OS=10.0,name=iPhone 6" 
-         - TEST_SDK=iphonesimulator
-         - SCHEME=TraceLog-iOS-Example 
-    - 
-      os: osx
-      osx_image: xcode9.3
-      env: 
-         - BUILD="xcodebuild"
-         - TEST_DEST="platform=iOS Simulator,OS=9.3,name=iPhone 6" 
-         - TEST_SDK=iphonesimulator
-         - SCHEME=TraceLog-iOS-Example 
-    - 
-      os: osx
-      osx_image: xcode9.3
-      env: 
-         - BUILD="xcodebuild"
-         - TEST_DEST="platform=iOS Simulator,OS=9.2,name=iPhone 5s" 
-         - TEST_SDK=iphonesimulator
-         - SCHEME=TraceLog-iOS-Example 
-    - 
-      os: osx
-      osx_image: xcode9.3
-      env: 
-         - BUILD="xcodebuild"
-         - TEST_DEST="platform=iOS Simulator,OS=9.0,name=iPhone 4s" 
-         - TEST_SDK=iphonesimulator
-         - SCHEME=TraceLog-iOS-Example 
-    - 
-      os: osx
-      osx_image: xcode9.3
-      env: 
-         - BUILD="xcodebuild"
-         - TEST_DEST="platform=OS X,arch=x86_64" 
+         - TEST_DEST="platform=OS X,arch=x86_64"
          - TEST_SDK=macosx
-         - SCHEME=TraceLog-OSX-Example 
+         - SCHEME=TraceLog-OSX-Example
 
 before_install:
   #
@@ -91,6 +52,17 @@ before_install:
        export BUNDLE_GEMFILE=Gemfile
        gem install bundler
        bundler install
+    fi
+  #
+  # OSX
+  #
+  - |
+    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
+       # Fix travis issue: https://github.com/travis-ci/travis-ci/issues/6307
+       rvm get head --auto-dotfiles || true
+       sudo log config --subsystem "xctest" --mode "persist:debug"
+       sudo log config --subsystem "TraceLog-OSX" --mode "persist:debug"
+       sudo log config --subsystem "TraceLog-iOS" --mode "persist:debug"
     fi
   #
   # Linux requires downloading Swift and tools
@@ -109,25 +81,22 @@ before_install:
 
 script:
   - |
-    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
-       # Fix travis issue: https://github.com/travis-ci/travis-ci/issues/6307
-       rvm get head --auto-dotfiles || true
-    fi
-  - |
     if [[ "$BUILD" == "swift build"  ]]; then
       swift test
     fi
   - |
     if [[ "$BUILD" == "pod lint" ]]; then
+        set -e  # Fail (and stop build) on first non zero exit code
         bundler exec pod repo update
         bundler exec pod lib lint
+        set +e
     fi
   - |
     if [[ "$BUILD" == "xcodebuild"  ]]; then
-        set -o pipefail
-        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" -enableCodeCoverage YES build-for-testing | bundler exec xcpretty
-        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" -enableCodeCoverage YES test              | bundler exec xcpretty
-        set +o pipefail
+        set -e  # Fail (and stop build) on first non zero exit code
+        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" -enableCodeCoverage YES build-for-testing
+        xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$TEST_DEST" -sdk "$TEST_SDK" -enableCodeCoverage YES test
+        set +e
     fi
 
 after_success:
